# Generated by Django 4.0.5 on 2022-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorstack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
